import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800"],
  fallback: ["sans-serif"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shool Management System | RA Darul Ulum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} max-w-[100vw] overflow-x-hidden antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
